### ISSUE TITLE
Loading results from +page.server.js causes Card components to not update.

### ISSUE THREAD

**Issue by figuerom16** [industry-standard-good-practice/lurker-for-reddit#5]
Hello, new to opening issues so I'm sorry if I'm not thorough enough in my explanation or doing this incorrectly.  I didn't want to do a pull request since it's broken.  Here is the fork in Gitlab https://gitlab.com/figuerom16/help (Sorry it's where I started at.  I'll create a fork in Github when I'm ready to do a PR).

The issue occurs when converting your src/routes/I/subreddit/+page.server.js to handle the initial fetch. Instead of using the api server.js.  The benefit is that it allows for a single round trip reducing the load time for subreddits.  The results are delivered through the export let data.results.  This loads correctly for the first 30 elements, the new results do update when fetching more results through the api or updating the results from +page.server.js for a new subreddit
$: Console.log(requests) does show results are being populated with more results or new results from other subreddits.

For some reason the Cards aren't updating.

**Comment by noahsemus** [comment]
Looking at your code, it seems fine to me. It's hard to say why as I can't test it out myself. If you create a PR I could run it locally and look into it more.

**Comment by figuerom16** [comment]
Closing issue in favor of PR.
